//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladder
    {
        public int clubID { get; set; }
        public Nullable<int> position { get; set; }
        public string clubName { get; set; }
        public Nullable<int> matchesPlayed { get; set; }
        public Nullable<int> win { get; set; }
        public Nullable<int> draw { get; set; }
        public Nullable<int> lost { get; set; }
        public Nullable<int> goalsFor { get; set; }
        public Nullable<int> goalsAgainst { get; set; }
        public Nullable<int> goalDifference { get; set; }
        public Nullable<int> points { get; set; }
        public string thumbnail { get; set; }
    }
}
